name: Run Tests on Dispatch

on:
  repository_dispatch:
    types:
      - run-tests
  workflow_dispatch: # Allows manual trigger

concurrency:
  group: run-tests-${{ github.event.client_payload.branch || github.run_id }}
  cancel-in-progress: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' 

      - name: Run Tests
        run: |
          echo "Running tests for the repository"
          go test -v ./...
       
