name: Run Tests for Autokitteh PRs

on:
  repository_dispatch:
    types:
      - run-tests
  workflow_dispatch: 

concurrency:
  group: run-tests-${{ github.event.client_payload.branch || 'manual-trigger'}}
  cancel-in-progress: false 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Autokitteh Repository
        uses: actions/checkout@v3
        with:
          repository: autokitteh/autokitteh
          ref: ${{ github.event.client_payload.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' 

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check for Stray Processes
        run: |
          echo "Checking for stray processes..."
          ps aux | grep ak || echo "No stray processes found"

      - name: Run Tests
        run: |
          echo "Running tests for Autokitteh repository"
          go test -v ./...
          lsof -i :6060
