name: Run Tests for Autokitteh PRs

on:
  repository_dispatch:
    types:
      - run-tests
  workflow_dispatch: 

concurrency:
  group: run-tests-${{ github.event.client_payload.branch || 'manual-trigger'}}
  cancel-in-progress: false 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Kittest Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch || 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Out Autokitteh Repository
        uses: actions/checkout@v4
        with:
          path: _autokitteh
          repository: autokitteh/autokitteh
          ref: ${{ github.event.client_payload.branch || 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' 

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Tests
        run: |
          echo "Running tests for Autokitteh repository"
          go test -v ./...
